# Generated by Django 4.1.5 on 2023-01-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='hire_data',
            new_name='hire_date',
        ),
    ]
